---
title: "Rozdział 1"
output:
  html_document: default
  html_notebook: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, cache=TRUE)
```

Aby zainstalować i włączyć pakiet `Przewodnik` wykonaj poniższe dwie liniki.

```
devtools::install_github("pbiecek/PrzewodnikPakiet")
library("Przewodnik")
```

Kody z rozdziału 1 ,,Przewodnika po programie R'' wydanie 4.

### Rozdział 1.2.1.1

```{r}
library("rvest")
wikiPL <- "https://pl.wikipedia.org/wiki/Reprezentacja_Polski_w_pi%C5%82ce_no%C5%BCnej"
webpage <- read_html(wikiPL)
table_links <- html_nodes(webpage, '.wikitable')
tables <- html_table(table_links, fill=TRUE)
FIFA_table <- which(sapply(tables, ncol) == 14)
tab <- tables[[FIFA_table]]
head(tab)
```

### Rozdział 1.2.1.2

```{r}
library("tidyr")
library("dplyr")
colnames(tab)[2:13] <- 1:12
data_long <- gather(tab[,1:13], Miesiac, Pozycja, -Rok)
data_long <- mutate(data_long, 
                    Pozycja = as.numeric(Pozycja),
                    Miesiac = as.numeric(Miesiac))
head(data_long, 3)
```

### Rozdział 1.2.1.3

```{r wczytywaniePPPR}
library("ggplot2")
ggplot(data_long, aes(factor(Rok), Pozycja)) +
  geom_boxplot() + ggtitle("Pozycja Polski w rankingu FIFA") +
  xlab("Data publikacji rankingu") + ylab("Pozycja Polski w rankingu")
```
