# Jak generować liczby losowe?

W wielu zagadnieniach, szczególnie tych związanych z modelowaniem metodami Monte Carlo bardzo złożonych zjawisk rzeczywistych (finansowych, biologicznych, fizycznych, chemicznych, meteorologicznych itp.), potrzebne są narzędzia pozwalające emulować losowość, tak aby odzwierciedlić stochastyczną naturę badanego zjawiska.
Dlatego też w wielu pakietach statystycznych oraz bibliotekach różnych języków programowania dostępne są funkcje do generowania liczb pseudolosowych, czyli liczb o właściwościach podobnych do prawdziwie losowych. 

Takie funkcje dostępne są również w programie R. W tym podrozdziale opiszemy podstawowe zagadnienia związane z generatorami liczb losowych, a w następnym podrozdziale przedstawimy funkcje do generowania liczb losowych z różnych popularnych rozkładów oraz do wyznaczania charakterystyk tych rozkładów.

Btw: Za autora metody Monte Carlo uznaje się polskiego matematyka Stanisława Ulama, który współpracując w Los Alamos z Enrico Fermim, John von Neumannem i Nicholasem Metropolisem, użył tej metody do modelowania reakcji łańcuchowej przebiegającej podczas wybuchu bomby wodorowej.
