# Jak korzystać z serwisu GitHub i Waffle?

Jeżeli pracujesz nad bardziej złożonym projektem lub pracujesz nad projektem w zespole to z pewnością potrzebujesz sprawdzić jakie zmiany, przez kogo i kiedy zostały wprowadzone do plików projektowych. Świetnym narzędziem do tego jest system git.

Git to rozproszony system kontroli wersji stworzony przez Linusa Torvaldsa `r citep(bib['gitWiki'])`. Jest otwartym oprogramowaniem dostępnym na licencji GNU GPL 2. Pozwala na zarządzanie i śledzenie zmian w plikach. Zazwyczaj są to pliki z kodami, np. w języku R lub innym jezyku programowania, ale mogą być to też inne pliki binarne.

Git jest systemem, który każdy może pobrać i zainstalować na swoim serwerze. Jednak na potrzeby mniejszych projektów wygodnie jest skorzystać z serwisu GitHub http://github.com/, który umożliwia korzystanie z systemu git bez konieczności samodzielnej instalacji.

Dane i kody na serwisie GitHub można przechowywać w publicznych repozytoriach (kazdy internauta widzi ich zawartość), co jest bezpłatne, lub w prywatnych repozytoriach (możemy określać kto co możę widzieć), lecz ta usługa jest już płatna. Poniżej opiszemy jak korzystać z bezpłatnych repozytoriów. 

## Struktura

Struktura GitHuba jest następująca.

Na najwyższym poziomie organizacji są konta, mogą być to konta osób (np. moje konto http://github.com/pbiecek) lub organizacji (np. konto grupy MI^2 http://github.com/mi2-warsaw).

W ramach kont można tworzyć repozytoria. Repozytoria mogą być publicze (widoczne dla wszystkich) lub prywatne. 









